name:               safeio
version:            0.0.5.0
synopsis:           Write output to disk atomically
description:        >
                    This package implements utilities to perform atomic output
                    so as to avoid the problem of partial intermediate files.

category:           IO
author:             Luis Pedro Coelho
maintainer:         Luis Pedro Coelho
license:            MIT
license-file:       COPYING
build-type:         Simple
github:             luispedro/safeio

extra-source-files:
 - README.md
 - ChangeLog
dependencies:
 - base > 4.8 && < 5
 - bytestring
 - directory
 - exceptions
 - filepath
 - unix
ghc-options:
 - -Wall
default-extensions:
  - BangPatterns
  - OverloadedStrings
  - CPP

flags:
  with-conduit:
    description: compile with support with conduit
    default: true
    manual: true

when:
  - condition: ! 'os(windows)'
    cpp-options:
      - -DWINDOWS
  - condition: 'flag(with-conduit)'
    dependencies:
     - conduit >= 1.0
     - conduit-combinators
     - resourcet

library:
  source-dirs:
   - ./
  exposed-modules:
      - System.IO.SafeWrite
  other-modules: []
  when:
    - condition: 'flag(with-conduit)'
      exposed-modules:
        - Data.Conduit.SafeWrite

tests:
  safeiotest:
    main: System/IO/SafeWrite/Tests.hs
    source-dirs:
     - ./test/
    other-modules: []
    dependencies:
      - safeio
      - HUnit
      - test-framework
      - test-framework-hunit

